<a href="https://colab.research.google.com/github/TheAraibKhan/Natural-Language-Processing-Lab/blob/main/NLP_Practical_08_Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Natural Language Processing Laboratory
#
# Practical 8: Bag-of-Words (BoW) Vectorization and Representation
#
# Name: Araib Khan
# Course: B.Tech CSE (Artificial Intelligence)
# Subject: Natural Language Processing Laboratory
# Practical No.: 8
# CO: CO2
#
# Objective:
# To convert text documents into numerical vectors using the
# Bag-of-Words representation.

In [2]:
!pip install -q scikit-learn

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

print("Library imported successfully.")

Library imported successfully.

In [4]:
documents = [
    "Natural language processing is interesting.",
    "Natural language processing is useful.",
    "Machine learning is useful for natural language processing."
]

print("Documents:")
for i, document in enumerate(documents, 1):
    print(f"Document {i}: {document}")

Documents:
Document 1: Natural language processing is interesting.
Document 2: Natural language processing is useful.
Document 3: Machine learning is useful for natural language processing.

In [5]:
vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(documents)

print("Bag-of-Words matrix created successfully.")

Bag-of-Words matrix created successfully.

In [6]:
vocabulary = vectorizer.get_feature_names_out()

print("Vocabulary:")
print(vocabulary)

Vocabulary:
['for' 'interesting' 'is' 'language' 'learning' 'machine' 'natural'
 'processing' 'useful']

In [7]:
print("Bag-of-Words Matrix:")
print(bow_matrix.toarray())

Bag-of-Words Matrix:
[[0 1 1 1 0 0 1 1 0]
 [0 0 1 1 0 0 1 1 1]
 [1 0 1 1 1 1 1 1 1]]

In [8]:
import pandas as pd

bow_table = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vocabulary
)

bow_table.index = [
    "Document 1",
    "Document 2",
    "Document 3"
]

print("Bag-of-Words Representation:")
display(bow_table)

Bag-of-Words Representation:

,for,interesting,is,language,learning,machine,natural,processing,useful
Document 1,0,1,1,1,0,0,1,1,0
Document 2,0,0,1,1,0,0,1,1,1
Document 3,1,0,1,1,1,1,1,1,1

In [9]:
print("Word Counts in Each Document:\n")

for i, document in enumerate(bow_matrix.toarray(), 1):
    print(f"Document {i}:")

    for word, count in zip(vocabulary, document):
        if count > 0:
            print(f"  {word} -> {count}")

    print()

Word Counts in Each Document:

Document 1:
  interesting -> 1
  is -> 1
  language -> 1
  natural -> 1
  processing -> 1

Document 2:
  is -> 1
  language -> 1
  natural -> 1
  processing -> 1
  useful -> 1

Document 3:
  for -> 1
  is -> 1
  language -> 1
  learning -> 1
  machine -> 1
  natural -> 1
  processing -> 1
  useful -> 1

In [10]:
new_document = [
    "Natural language processing is useful."
]

new_bow = vectorizer.transform(new_document)

print("New Document:")
print(new_document[0])

print("\nBoW Representation:")
print(new_bow.toarray())

New Document:
Natural language processing is useful.

BoW Representation:
[[0 0 1 1 0 0 1 1 1]]

In [11]:
new_bow_table = pd.DataFrame(
    new_bow.toarray(),
    columns=vocabulary
)

display(new_bow_table)

,for,interesting,is,language,learning,machine,natural,processing,useful
0,0,0,1,1,0,0,1,1,1

In [12]:
print("Vocabulary Index:")
print()

for index, word in enumerate(vocabulary):
    print(f"{index} -> {word}")

Vocabulary Index:

0 -> for
1 -> interesting
2 -> is
3 -> language
4 -> learning
5 -> machine
6 -> natural
7 -> processing
8 -> useful

In [13]:
# Result:
# The given text documents were successfully converted into numerical
# representations using the Bag-of-Words model.
#
# Conclusion:
# The Bag-of-Words model represents text using word-frequency counts.
# It converts unstructured text into numerical vectors that can be used
# as input for classical machine learning and NLP algorithms.