<a href="https://colab.research.google.com/github/TheAraibKhan/Natural-Language-Processing-Lab/blob/main/NLP_Practical_15_Text_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Natural Language Processing Laboratory
#
# Practical 15: Text Classification using Naïve Bayes/SVM with TF-IDF
#
# Name: Araib Khan
# Course: B.Tech CSE (Artificial Intelligence)
# Subject: Natural Language Processing Laboratory
# Practical No.: 15
# CO: CO2
#
# Objective:
# To classify text documents using TF-IDF feature representation with
# Multinomial Naïve Bayes and Support Vector Machine classifiers.

In [2]:
!pip install -q scikit-learn pandas

In [3]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Libraries imported successfully.")

Libraries imported successfully.

In [4]:
texts = [
    "Artificial intelligence is transforming modern technology.",
    "Machine learning algorithms are used to analyze large datasets.",
    "Deep learning models are used in computer vision applications.",
    "Natural language processing helps computers understand human language.",
    "Python is widely used for machine learning and data science.",
    "Cloud computing provides scalable computing resources.",
    "Software engineers develop applications using programming languages.",
    "Data science combines statistics programming and machine learning.",

    "Football is one of the most popular sports in the world.",
    "The cricket team won the match after scoring many runs.",
    "The player scored a goal in the final minute of the game.",
    "Basketball players practice shooting and defensive techniques.",
    "The tennis tournament attracted many professional players.",
    "The team trained hard before the championship match.",
    "The athlete won a gold medal in the competition.",
    "Cricket players improve their batting and bowling skills."
]

labels = [
    "Technology",
    "Technology",
    "Technology",
    "Technology",
    "Technology",
    "Technology",
    "Technology",
    "Technology",

    "Sports",
    "Sports",
    "Sports",
    "Sports",
    "Sports",
    "Sports",
    "Sports",
    "Sports"
]

data = pd.DataFrame({
    "Text": texts,
    "Category": labels
})

print("Dataset:")
display(data)

Dataset:

                                                 Text    Category
0   Artificial intelligence is transforming modern...  Technology
1   Machine learning algorithms are used to analyz...  Technology
2   Deep learning models are used in computer visi...  Technology
3   Natural language processing helps computers un...  Technology
4   Python is widely used for machine learning and...  Technology
5   Cloud computing provides scalable computing re...  Technology
6   Software engineers develop applications using ...  Technology
7   Data science combines statistics programming a...  Technology
8   Football is one of the most popular sports in ...      Sports
9   The cricket team won the match after scoring m...      Sports
10  The player scored a goal in the final minute o...      Sports
11  Basketball players practice shooting and defen...      Sports
12  The tennis tournament attracted many professio...      Sports
13  The team trained hard before the championship ...      Sports
14   The athlete won a gold medal in the competition.      Sports
15  Cricket players improve their batting and bowl...      Sports

In [5]:
print("Class Distribution:")
print(data["Category"].value_counts())

Class Distribution:
Category
Technology    8
Sports        8
Name: count, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    data["Text"],
    data["Category"],
    test_size=0.25,
    random_state=42,
    stratify=data["Category"]
)

print("Training samples:", len(X_train))
print("Testing samples :", len(X_test))

Training samples: 12
Testing samples : 4

In [7]:
tfidf_vectorizer = TfidfVectorizer()

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("TF-IDF vectorization completed.")
print("Training matrix shape:", X_train_tfidf.shape)
print("Testing matrix shape :", X_test_tfidf.shape)

TF-IDF vectorization completed.
Training matrix shape: (12, 73)
Testing matrix shape : (4, 73)

In [8]:
feature_names = tfidf_vectorizer.get_feature_names_out()

print("TF-IDF Vocabulary:\n")
print(feature_names)

TF-IDF Vocabulary:

['after' 'and' 'applications' 'are' 'artificial' 'attracted' 'batting'
 'before' 'bowling' 'championship' 'cloud' 'combines' 'computer'
 'computers' 'computing' 'cricket' 'data' 'deep' 'final' 'football' 'for'
 'game' 'goal' 'hard' 'helps' 'human' 'improve' 'in' 'intelligence' 'is'
 'language' 'learning' 'machine' 'many' 'match' 'minute' 'models' 'modern'
 'most' 'natural' 'of' 'one' 'player' 'players' 'popular' 'processing'
 'professional' 'programming' 'provides' 'python' 'resources' 'runs'
 'scalable' 'science' 'scored' 'scoring' 'skills' 'sports' 'statistics'
 'team' 'technology' 'tennis' 'the' 'their' 'tournament' 'trained'
 'transforming' 'understand' 'used' 'vision' 'widely' 'won' 'world']

In [9]:
tfidf_table = pd.DataFrame(
    X_train_tfidf.toarray(),
    columns=feature_names
)

print("First Training Document - TF-IDF Representation:")
display(tfidf_table.head(1).round(3))

First Training Document - TF-IDF Representation:

,after,and,applications,are,artificial,attracted,batting,before,bowling,championship,...,their,tournament,trained,transforming,understand,used,vision,widely,won,world
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

print("Multinomial Naïve Bayes model trained successfully.")

Multinomial Naïve Bayes model trained successfully.

In [11]:
nb_predictions = nb_model.predict(X_test_tfidf)

print("Naïve Bayes Predictions:")
print(nb_predictions)

Naïve Bayes Predictions:
['Sports' 'Technology' 'Sports' 'Technology']

In [12]:
nb_accuracy = accuracy_score(y_test, nb_predictions)

print("Naïve Bayes Accuracy:")
print(f"{nb_accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, nb_predictions))

Naïve Bayes Accuracy:
1.0000

Classification Report:
              precision    recall  f1-score   support

      Sports       1.00      1.00      1.00         2
  Technology       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

In [13]:
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

print("Linear SVM model trained successfully.")

Linear SVM model trained successfully.

In [14]:
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

print("Linear SVM model trained successfully.")

Linear SVM model trained successfully.

In [15]:
svm_predictions = svm_model.predict(X_test_tfidf)

print("SVM Predictions:")
print(svm_predictions)

SVM Predictions:
['Sports' 'Technology' 'Sports' 'Technology']

In [16]:
svm_accuracy = accuracy_score(y_test, svm_predictions)

print("SVM Accuracy:")
print(f"{svm_accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, svm_predictions))

SVM Accuracy:
1.0000

Classification Report:
              precision    recall  f1-score   support

      Sports       1.00      1.00      1.00         2
  Technology       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

In [17]:
comparison = pd.DataFrame({
    "Classifier": [
        "Multinomial Naïve Bayes",
        "Linear SVM"
    ],
    "Accuracy": [
        nb_accuracy,
        svm_accuracy
    ]
})

print("Classifier Comparison:")
display(comparison.round(4))

Classifier Comparison:

                Classifier  Accuracy
0  Multinomial Naïve Bayes       1.0
1               Linear SVM       1.0

In [18]:
nb_cm = confusion_matrix(y_test, nb_predictions)
svm_cm = confusion_matrix(y_test, svm_predictions)

print("Naïve Bayes Confusion Matrix:")
print(nb_cm)

print("\nLinear SVM Confusion Matrix:")
print(svm_cm)

Naïve Bayes Confusion Matrix:
[[2 0]
 [0 2]]

Linear SVM Confusion Matrix:
[[2 0]
 [0 2]]

In [19]:
new_text = [
    "The software uses machine learning algorithms to process data.",
    "The football player scored two goals in the match."
]

new_text_tfidf = tfidf_vectorizer.transform(new_text)

nb_new_predictions = nb_model.predict(new_text_tfidf)

print("New Text Classification using Naïve Bayes:\n")

for text, prediction in zip(new_text, nb_new_predictions):
    print(f"Text: {text}")
    print(f"Predicted Category: {prediction}\n")

New Text Classification using Naïve Bayes:

Text: The software uses machine learning algorithms to process data.
Predicted Category: Technology

Text: The football player scored two goals in the match.
Predicted Category: Sports

In [20]:
svm_new_predictions = svm_model.predict(new_text_tfidf)

print("New Text Classification using SVM:\n")

for text, prediction in zip(new_text, svm_new_predictions):
    print(f"Text: {text}")
    print(f"Predicted Category: {prediction}\n")

New Text Classification using SVM:

Text: The software uses machine learning algorithms to process data.
Predicted Category: Technology

Text: The football player scored two goals in the match.
Predicted Category: Sports

In [21]:
prediction_table = pd.DataFrame({
    "Text": new_text,
    "Naïve Bayes": nb_new_predictions,
    "SVM": svm_new_predictions
})

display(prediction_table)

                                                Text Naïve Bayes         SVM
0  The software uses machine learning algorithms ...  Technology  Technology
1  The football player scored two goals in the ma...      Sports      Sports

In [22]:
print("Model Summary")
print("-" * 45)

print(f"Training Samples : {len(X_train)}")
print(f"Testing Samples  : {len(X_test)}")
print(f"Vocabulary Size  : {len(feature_names)}")

print(f"\nNaïve Bayes Accuracy : {nb_accuracy:.4f}")
print(f"SVM Accuracy         : {svm_accuracy:.4f}")

Model Summary
---------------------------------------------
Training Samples : 12
Testing Samples  : 4
Vocabulary Size  : 73

Naïve Bayes Accuracy : 1.0000
SVM Accuracy         : 1.0000

In [23]:
# Result:
# The given text dataset was successfully converted into TF-IDF feature
# vectors and classified using Multinomial Naïve Bayes and Linear SVM.
#
# Both classifiers were trained on the TF-IDF representation and
# evaluated using accuracy, classification reports, and confusion matrices.
#
# Conclusion:
# TF-IDF provides a numerical representation of text that can be used
# effectively with classical machine learning algorithms. Multinomial
# Naïve Bayes and Linear SVM are standard approaches for text classification.
# The trained models can also be used to classify previously unseen text.